
// USER AUTHENTICATION
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";

// FILTER DEALS
export const SET_STORE_ID_FILTER = "SET_STORE_ID_FILTER";
export const SET_PRICE_FILTER = "SET_PRICE_FILTER";

// SORT DEALS
export const SET_DEALS_ORDER = "SET_DEALS_ORDER";

// DEALS PAGINATION
export const SET_ALL_DEALS = "SET_ALL_DEALS";
export const SET_OFFSET = "SET_OFFSET";
export const SET_NO_MORE_DEALS = "SET_NO_MORE_DEALS";